const axios = require('axios');
const WorkoutPlan = require('../models/WorkoutPlan');
const UserDietPlan = require('../models/UserDietPlan');
const dietCalculator = require('./dietCalculator');
const { generateDietPlan } = require('./dietPlanCalculator');

const ML_API_URL = process.env.ML_API_URL || 'http://127.0.0.1:5001';

const experienceMap = {
  beginner: 1,
  intermediate: 2,
  advanced: 3
};

const goalMap = {
  'fat loss': 1,
  'muscle gain': 2,
  'maintenance': 3
};

// ─── HELPERS ────────────────────────────────────────────────────────────────

const isArrayEqual = (arr1, arr2) => {
  const a = Array.isArray(arr1) ? arr1 : (arr1 ? [arr1] : []);
  const b = Array.isArray(arr2) ? arr2 : (arr2 ? [arr2] : []);
  return JSON.stringify([...a].sort()) === JSON.stringify([...b].sort());
};

const normalizeGoal = (goal) => {
  if (!goal) return 'maintenance';
  const lower = goal.toLowerCase();
  if (lower.includes('weight')) return 'fat loss';
  if (lower.includes('muscle')) return 'muscle gain';
  return 'maintenance';
};

const normalizeGoalLabel = (goal) => {
  const normalized = normalizeGoal(goal);
  if (normalized === 'fat loss') return 'Weight Loss';
  if (normalized === 'muscle gain') return 'Muscle Gain';
  return 'Maintenance';
};

const normalizeExperience = (experience) => {
  if (!experience) return 'intermediate';
  return experience.toLowerCase();
};

const normalizeExperienceLabel = (experience) => {
  const normalized = normalizeExperience(experience);
  if (normalized === 'beginner') return 'Beginner';
  if (normalized === 'advanced') return 'Advanced';
  return 'Intermediate';
};

const normalizeActivityLevel = (activityLevel) => {
  const normalized = (activityLevel || 'moderate').toLowerCase().replace(/\s+/g, '_');
  if (['sedentary', 'light', 'moderate', 'active', 'very_active'].includes(normalized)) {
    return normalized;
  }
  if (normalized.includes('very')) return 'very_active';
  return 'moderate';
};

const normalizeDietType = (dietType) => {
  if (!dietType) return 'vegetarian';
  const d = String(dietType).toLowerCase().trim();
  if (d.includes('vegan')) return 'vegan';
  if (d.includes('non') || d.includes('meat') || d.includes('omnivore') || d.includes('non-veg') || d.includes('nonveget')) return 'non-vegetarian';
  if (d.includes('veget')) return 'vegetarian';
  return 'vegetarian';
};

const getMondayStart = (date = new Date()) => {
  const result = new Date(date);
  result.setHours(0, 0, 0, 0);
  const day = result.getDay();
  const diff = (day + 6) % 7;
  result.setDate(result.getDate() - diff);
  return result;
};

// ─── SAFE toObject HELPER ────────────────────────────────────────────────────
// Works whether the value is a Mongoose document, a Mongoose subdoc,
// or a plain JavaScript object (e.g. after .lean() or a spread).

const toPlainObject = (value) => {
  if (value === null || value === undefined) return value;
  if (typeof value.toObject === 'function') return value.toObject();
  if (typeof value === 'object') return { ...value };
  return value;
};

// ─── DIFFICULTY COEFFICIENT ──────────────────────────────────────────────────

const fetchUpdatedCoefficient = async (averageDifficulty, currentCoefficient = 1.0) => {
  try {
    const response = await axios.post(`${ML_API_URL}/scale-difficulty`, {
      average_difficulty: averageDifficulty
    }, { timeout: 4000 });
    return response.data.new_difficulty_coefficient || currentCoefficient;
  } catch (err) {
    console.warn('scale-difficulty service unavailable:', err.message);
    // Inline fallback mirrors Flask logic
    if (averageDifficulty < 4) return Math.min((currentCoefficient * 1.15), 1.5);
    if (averageDifficulty > 7) return Math.max((currentCoefficient * 0.85), 0.6);
    return currentCoefficient;
  }
};

// ─── APPLY COEFFICIENT TO A SAVED PLAN ──────────────────────────────────────

const applyDifficultyScalingToPlan = async (userId, dayIndex, averageDifficulty) => {
  const plan = await WorkoutPlan.findOne({ user: userId, isAutoGenerated: true });
  if (!plan || !Array.isArray(plan.weeklyPlan)) {
    console.warn('applyDifficultyScalingToPlan: no plan found');
    return null;
  }

  const currentCoefficient = plan.difficultyCoefficient || 1.0;
  const newCoefficient = await fetchUpdatedCoefficient(averageDifficulty, currentCoefficient);

  console.log(`📊 Difficulty rating: ${averageDifficulty} | Coefficient: ${currentCoefficient} → ${newCoefficient}`);

  // Scale sets & reps on every future, non-rest, not-yet-completed day
  const updatedWeeklyPlan = plan.weeklyPlan.map((day, idx) => {
    if (idx <= dayIndex) return day;        // past days — leave untouched
    if (day.type === 'rest') return day;    // rest days — nothing to scale
    if (day.completed) return day;          // already done — don't touch

    // ✅ FIX: Use toPlainObject() instead of day.toObject() so this works
    //         whether `day` is a Mongoose subdoc OR a plain JS object.
    const dayObj = toPlainObject(day);

    const scaledExercises = (dayObj.exercises || []).map(ex => {
      // ✅ FIX: Same safe conversion for each exercise subdoc.
      const exObj = toPlainObject(ex);
      return {
        ...exObj,
        sets: Math.max(1, Math.round((exObj.sets || 3) * newCoefficient)),
        reps: Math.max(1, Math.round((exObj.reps || 10) * newCoefficient))
      };
    });

    return { ...dayObj, exercises: scaledExercises };
  });

  plan.weeklyPlan = updatedWeeklyPlan;
  plan.difficultyCoefficient = newCoefficient;
  await plan.save();

  console.log(`✅ Difficulty scaling applied to days after index ${dayIndex}`);
  return plan;
};

// ─── DIET HELPERS ────────────────────────────────────────────────────────────

const getMealDescription = (food, preferences, dietType) => {
  let updated = food;
  const type = normalizeDietType(dietType);

  if (preferences.lactoseFree || type === 'vegan') {
    updated = updated.replace(/Greek yogurt/gi, 'coconut yogurt');
    updated = updated.replace(/cottage cheese/gi, 'tofu scramble');
    updated = updated.replace(/(?<!almond )\bmilk\b/gi, 'almond milk');
    updated = updated.replace(/cheese/gi, 'dairy-free cheese');
  }

  if (preferences.nutAllergy) {
    updated = updated.replace(/almond|walnut|cashew|peanut|nut/gi, 'seed');
  }

  if (preferences.sugarFree) {
    updated = updated.replace(/honey|maple syrup|brown sugar|sweet chili/gi, 'cinnamon');
  }

  if (preferences.noOnion || preferences.noGarlic) {
    updated = updated.replace(/with garlic|with onion|sautéed onions|garlic/gi, 'savory herbs');
  }

  if (type === 'vegetarian' || type === 'vegan') {
    const vegReplacements = [
      { find: /\bgrilled chicken\b/gi, replace: type === 'vegan' ? 'grilled tofu' : 'grilled soyachap' },
      { find: /\bchicken salad\b/gi,   replace: type === 'vegan' ? 'tofu salad'   : 'soyachap salad'   },
      { find: /\bchicken sandwich\b/gi, replace: type === 'vegan' ? 'tofu sandwich' : 'soyachap sandwich' },
      { find: /\bchicken wrap\b/gi,    replace: type === 'vegan' ? 'tofu wrap'    : 'soyachap wrap'    },
      { find: /\bchicken curry\b/gi,   replace: type === 'vegan' ? 'tofu curry'   : 'soyachap curry'   },
      { find: /\bgrilled fish\b/gi,    replace: type === 'vegan' ? 'grilled tofu' : 'grilled mushroom' },
      { find: /\bfish fry\b/gi,        replace: type === 'vegan' ? 'tofu fry'     : 'mushroom fry'     },
      { find: /\bfish curry\b/gi,      replace: type === 'vegan' ? 'tofu curry'   : 'mushroom curry'   },
      { find: /\bchicken\b/gi,         replace: type === 'vegan' ? 'tofu'         : 'soyachap'         },
      { find: /\bfish\b/gi,            replace: type === 'vegan' ? 'tofu'         : 'mushroom'         },
      { find: /\bsalmon\b/gi,          replace: type === 'vegan' ? 'tofu'         : 'mushroom'         },
      { find: /\btuna\b/gi,            replace: type === 'vegan' ? 'tofu'         : 'mushroom'         },
      { find: /\bshrimp\b/gi,          replace: type === 'vegan' ? 'tofu'         : 'mushroom'         },
      { find: /\b(egg|eggs)\b/gi,      replace: type === 'vegan' ? 'tofu'         : 'paneer'           },
      { find: /\bbeef\b/gi,            replace: type === 'vegan' ? 'tofu'         : 'paneer'           },
      { find: /\bpork\b/gi,            replace: type === 'vegan' ? 'tofu'         : 'paneer'           },
      { find: /\bbacon\b/gi,           replace: type === 'vegan' ? 'tofu'         : 'paneer'           },
      { find: /\bturkey\b/gi,          replace: type === 'vegan' ? 'tofu'         : 'paneer'           },
      { find: /\bsausage\b/gi,         replace: type === 'vegan' ? 'tofu'         : 'paneer'           }
    ];

    vegReplacements.forEach(({ find, replace }) => {
      updated = updated.replace(find, replace);
    });
  }

  return updated.replace(/\s+\s+/g, ' ').trim();
};

const sanitizeDietPlanForPreferences = (weeklyPlan, dietType, preferences) => {
  if (!Array.isArray(weeklyPlan)) return weeklyPlan;

  const sanitizeText = (value) => {
    if (typeof value !== 'string') return value;
    return getMealDescription(value, preferences, dietType);
  };

  return weeklyPlan.map((day) => {
    if (!day || typeof day !== 'object') return day;

    const sanitizedDay = { ...day };

    if (Array.isArray(day.meals)) {
      sanitizedDay.meals = day.meals.map((meal) => {
        if (!meal || typeof meal !== 'object') {
          return typeof meal === 'string' ? sanitizeText(meal) : meal;
        }
        return {
          ...meal,
          food:  meal.food  ? sanitizeText(meal.food)  : meal.food,
          name:  meal.name  ? sanitizeText(meal.name)  : meal.name,
          notes: meal.notes ? sanitizeText(meal.notes) : meal.notes
        };
      });
    } else if (typeof day.meals === 'string') {
      sanitizedDay.meals = sanitizeText(day.meals);
    }

    sanitizedDay.title       = day.title       ? sanitizeText(day.title)       : day.title;
    sanitizedDay.notes       = day.notes       ? sanitizeText(day.notes)       : day.notes;
    sanitizedDay.description = day.description ? sanitizeText(day.description) : day.description;
    sanitizedDay.food        = day.food        ? sanitizeText(day.food)        : day.food;

    return sanitizedDay;
  });
};

const getWeeklyDietTemplates = (dietType, preferences) => {
  const type = normalizeDietType(dietType);

  const vegetarianBreakfasts = [
    'Oatmeal with berries and almond milk',
    'Avocado toast with tomato and seeds',
    'Greek yogurt parfait with granola',
    'Vegetable omelette with spinach and mushrooms',
    'Chia pudding with mixed berries',
    'Banana pancakes with cinnamon',
    'Smoothie bowl with spinach and mango'
  ];
  const nonVegetarianBreakfasts = [
    'Egg scramble with spinach and whole grain toast',
    'Greek yogurt parfait with berries',
    'Smoked salmon and avocado toast',
    'Chicken sausage breakfast burrito bowl',
    'Scrambled eggs with veggies and turkey bacon',
    'Breakfast quesadilla with eggs and cheese',
    'Protein smoothie with banana and peanut butter'
  ];
  const vegetarianLunches = [
    'Quinoa and chickpea salad with roasted vegetables',
    'Lentil curry with brown rice',
    'Vegetable stir-fry with tofu and broccoli',
    'Hummus bowl with falafel and greens',
    'Sweet potato and black bean tacos',
    'Vegetarian buddha bowl with quinoa',
    'Spinach and feta stuffed peppers'
  ];
  const nonVegetarianLunches = [
    'Grilled chicken salad with mixed greens',
    'Turkey and avocado wrap',
    'Salmon bowl with brown rice and greens',
    'Chicken stir-fry with vegetables',
    'Beef and vegetable quinoa bowl',
    'Shrimp and avocado salad',
    'Chicken burrito bowl with salsa'
  ];
  const vegetarianSnacks = [
    'Apple slices with almond butter',
    'Cottage cheese with cucumber and herbs',
    'Mixed berries with Greek yogurt',
    'Hummus with carrot sticks',
    'Trail mix with seeds and dried fruits',
    'Celery with peanut butter',
    'Edamame with sea salt'
  ];
  const nonVegetarianSnacks = [
    'Hard-boiled eggs with pepper',
    'Turkey roll-ups with veggies',
    'Greek yogurt with berries',
    'Tuna salad cucumber boats',
    'Smoked salmon on crispbread',
    'Chicken salad lettuce cups',
    'Protein shake with fruit'
  ];
  const vegetarianDinners = [
    'Baked tofu with roasted vegetables',
    'Mushroom and lentil shepherd\'s pie',
    'Zucchini noodles with tomato basil sauce',
    'Vegetable curry with chickpeas',
    'Stuffed bell peppers with quinoa',
    'Butternut squash risotto',
    'Portobello mushroom burger with salad'
  ];
  const nonVegetarianDinners = [
    'Baked salmon with asparagus',
    'Turkey chili with mixed beans',
    'Grilled chicken with sweet potato',
    'Beef stir-fry with broccoli',
    'Shrimp tacos with avocado salsa',
    'Chicken breast with quinoa and greens',
    'Pork tenderloin with roasted vegetables'
  ];

  if (type === 'vegan') {
    return {
      breakfasts: vegetarianBreakfasts.map(s => s.replace(/Greek yogurt|Cottage cheese|egg|omelette/gi, (m) => {
        if (/Greek yogurt|Cottage cheese/gi.test(m)) return 'coconut yogurt';
        return 'tofu scramble';
      })),
      lunches:  vegetarianLunches.map(s => s.replace(/paneer|cottage cheese|egg/gi, 'tofu')),
      snacks:   vegetarianSnacks.map(s => s.replace(/Greek yogurt|cottage cheese|peanut butter/gi, (m) => m.toLowerCase().includes('peanut') ? 'seed butter' : 'coconut yogurt')),
      dinners:  vegetarianDinners.map(s => s.replace(/paneer|cheese|egg/gi, 'tofu')),
      preferences,
      type
    };
  }

  if (type === 'vegetarian') {
    return { breakfasts: vegetarianBreakfasts, lunches: vegetarianLunches, snacks: vegetarianSnacks, dinners: vegetarianDinners, preferences, type };
  }

  return { breakfasts: nonVegetarianBreakfasts, lunches: nonVegetarianLunches, snacks: nonVegetarianSnacks, dinners: nonVegetarianDinners, preferences, type };
};

const createDailyDietDay = (dayIndex, calories, dietType, preferences, macros) => {
  const template = getWeeklyDietTemplates(dietType, preferences);
  const breakfast = getMealDescription(template.breakfasts[dayIndex % template.breakfasts.length], preferences, template.type);
  const lunch     = getMealDescription(template.lunches[dayIndex % template.lunches.length],       preferences, template.type);
  const snack     = getMealDescription(template.snacks[dayIndex % template.snacks.length],         preferences, template.type);
  const dinner    = getMealDescription(template.dinners[dayIndex % template.dinners.length],       preferences, template.type);

  const ratios       = [0.25, 0.35, 0.15, 0.25];
  const mealCalories = ratios.map((r) => Math.round(calories * r));
  const caloriesTotal = mealCalories.reduce((sum, val) => sum + val, 0);

  return {
    day: `Day ${dayIndex + 1}`,
    totalCalories: caloriesTotal,
    macros,
    meals: [
      { type: 'Breakfast', food: breakfast, cal: `${mealCalories[0]} kcal` },
      { type: 'Lunch',     food: lunch,     cal: `${mealCalories[1]} kcal` },
      { type: 'Snack',     food: snack,     cal: `${mealCalories[2]} kcal` },
      { type: 'Dinner',    food: dinner,    cal: `${mealCalories[3]} kcal` }
    ]
  };
};

const isFlatWeeklyPlan = (weeklyPlan) => {
  if (!Array.isArray(weeklyPlan) || weeklyPlan.length !== 7) return true;
  const reference = JSON.stringify(weeklyPlan[0]?.meals || []);
  return weeklyPlan.every((day) => JSON.stringify(day.meals || []) === reference);
};

// ─── ML WORKOUT FETCH ────────────────────────────────────────────────────────

const getMLWorkoutRecommendation = async (user) => {
  try {
    const response = await axios.post(`${ML_API_URL}/recommend-plan`, {
      age:              Number(user.age)    || 25,
      weight_kg:        Number(user.weight) || 70,
      experience_level: experienceMap[normalizeExperience(user.experience)] || 2,
      goal_type:        goalMap[normalizeGoal(user.goal)] || 3,
      disease:  (user.medicalConditions && user.medicalConditions.length > 0) ? user.medicalConditions.join(' ') : 'none',
      injury:   (user.injuries          && user.injuries.length          > 0) ? user.injuries.join(' ')          : 'none',
      exhausted_muscles: []
    }, { timeout: 6000 });

    const data = response.data;
    if (!data) throw new Error('Empty ML response');

    return {
      recommendationId: data.recommended_cluster_index || null,
      routine:          data.base_routine               || null,
      planMeta:         data.medical_mutations_applied  || null
    };
  } catch (error) {
    console.warn('Workout plan recommendation service unavailable:', error.message || error);
    return { recommendationId: null, routine: null, planMeta: null };
  }
};

// ─── MUSCLE INFERENCE ────────────────────────────────────────────────────────

const inferMuscleGroup = (text) => {
  const lower = String(text || '').toLowerCase();
  if (/chest|pec|bench/.test(lower))                              return 'chest';
  if (/back|row|pull|lat/.test(lower))                            return 'back';
  if (/shoulder|press|overhead|lateral/.test(lower))              return 'shoulders';
  if (/bicep|curl/.test(lower))                                   return 'biceps';
  if (/tricep|dip|pushdown/.test(lower))                          return 'triceps';
  if (/squat|quad|leg|lunge|press/.test(lower))                   return 'quads';
  if (/deadlift|hamstring|romanian|glute/.test(lower))            return 'hamstrings';
  if (/calf|heel/.test(lower))                                    return 'calves';
  if (/core|plank|crunch|twist|ab|sit-up/.test(lower))            return 'core';
  if (/yoga|stretch|mobility|walking|jog|cycle|run/.test(lower))  return 'full body';
  return 'full body';
};

// ─── BUILD WEEKLY WORKOUT PLAN ───────────────────────────────────────────────

const buildWeeklyWorkoutPlan = (user, routineDict, planMeta, difficultyCoefficient = 1.0) => {
  const goal       = normalizeGoal(user.goal);
  const experience = normalizeExperience(user.experience);

  let baseSets = 3;
  let baseReps = 12;
  if (experience === 'beginner') { baseSets = 2; baseReps = 15; }
  if (experience === 'advanced') { baseSets = 4; baseReps = 8;  }

  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

  return days.map((dayName, idx) => {
    const rawExercises = (routineDict && routineDict[dayName]) ? routineDict[dayName] : 'Push Ups, Squats, Planks';
    const isRestDay    = rawExercises.toLowerCase() === 'rest' || rawExercises.toLowerCase().includes('rest day');

    let parsedExercises = [];
    let focusMuscles    = new Set();

    if (!isRestDay) {
      parsedExercises = rawExercises.split(',').map((ex, i) => {
        const cleanName = ex.trim();
        const muscle    = inferMuscleGroup(cleanName);
        focusMuscles.add(muscle);

        let dynamicSets = baseSets;
        let dynamicReps = baseReps;

        if (i === 0) {
          dynamicSets = Math.max(baseSets, 3);
          dynamicReps = Math.min(baseReps, 8);
        } else if (goal === 'fat loss') {
          dynamicReps = 15;
        } else if (goal === 'muscle gain') {
          dynamicSets = Math.min(baseSets + 1, 5);
          dynamicReps = 10;
        }

        if (muscle === 'core' || muscle === 'calves') {
          dynamicReps = 15 + Math.floor(Math.random() * 6);
        }

        dynamicSets = Math.max(1, Math.round(dynamicSets * difficultyCoefficient));
        dynamicReps = Math.max(1, Math.round(dynamicReps * difficultyCoefficient));

        return {
          name:        cleanName,
          sets:        dynamicSets,
          reps:        dynamicReps,
          muscleGroup: muscle
        };
      });
    }

    const title = isRestDay ? 'Rest & Recovery' : `${dayName} Training`;

    let medicalNotes = '';
    if (planMeta && planMeta.length > 0) {
      medicalNotes = `Medical Protocol Active: ${planMeta.join(' ')}`;
    } else if (goal === 'fat loss') {
      medicalNotes = 'Keep rest periods short (45s) to maintain elevated heart rate.';
    } else if (goal === 'muscle gain') {
      medicalNotes = 'Focus on eccentric control. Rest 90-120s between heavy sets.';
    }

    const weekStart = getMondayStart();
    const date      = new Date(weekStart);
    date.setDate(date.getDate() + idx);
    const isoDate   = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
    const today     = new Date();
    today.setHours(0, 0, 0, 0);

    return {
      date:               isoDate,
      dayName:            title === 'Rest & Recovery' ? 'Rest Day' : date.toLocaleDateString('en-US', { weekday: 'long' }),
      isToday:            isoDate === today.toISOString().slice(0, 10),
      dayIndex:           idx,
      title,
      type:               isRestDay ? 'rest' : 'strength',
      focusMuscles:       isRestDay ? ['rest'] : Array.from(focusMuscles),
      exercises:          parsedExercises,
      notes:              medicalNotes,
      completed:          false,
      completedExercises: [],
      difficultyRating:   null
    };
  });
};

// ─── GENERATE & SAVE WORKOUT ─────────────────────────────────────────────────

const generateAndSaveWorkoutPlan = async (user) => {
  const mlRecommendation = await getMLWorkoutRecommendation(user);

  console.log('==== ML WORKOUT DEBUG ====');
  console.log('Full ML response:', mlRecommendation);
  console.log('==========================');

  const weeklyPlan = buildWeeklyWorkoutPlan(
    user,
    mlRecommendation.routine,
    mlRecommendation.planMeta,
    1.0
  );

  const filter  = { user: user._id, isAutoGenerated: true };

  const payload = {
    user:             user._id,
    title:            `${user.name || 'User'} Weekly Workout Plan`,
    goal:             normalizeGoalLabel(user.goal),
    experienceLevel:  normalizeExperienceLabel(user.experience),
    durationWeeks:    4,
    daysPerWeek:      5,
    isAutoGenerated:  true,
    weeklyPlan,
    difficultyCoefficient: 1.0,
    generatedAt:      new Date(),
    planSource:       'ml',
    recommendationId: mlRecommendation.recommendationId ? String(mlRecommendation.recommendationId) : null,
    profileSnapshot:  {
      goal:              user.goal,
      experience:        user.experience,
      injuries:          user.injuries          || ['Regular'],
      medicalConditions: user.medicalConditions || ['Regular']
    }
  };

  await WorkoutPlan.replaceOne(filter, payload, { upsert: true });
  const updatedPlan = await WorkoutPlan.findOne(filter);

  if (!updatedPlan.weeklyPlan || updatedPlan.weeklyPlan.length !== 7) {
    throw new Error('Invalid weeklyPlan generated by ML layer');
  }

  console.log('✅ WORKOUT PLAN SAVED');
  return updatedPlan;
};

// ─── GET OR CREATE WORKOUT ───────────────────────────────────────────────────

const getOrCreateWorkoutPlan = async (user) => {
  let plan = await WorkoutPlan.findOne({ user: user._id, isAutoGenerated: true });

  const shouldRegenerate =
    !plan ||
    !Array.isArray(plan.weeklyPlan) ||
    plan.weeklyPlan.length !== 7 ||
    !plan.profileSnapshot ||
    plan.profileSnapshot.goal       !== user.goal       ||
    plan.profileSnapshot.experience !== user.experience ||
    !isArrayEqual(plan.profileSnapshot?.injuries,          user.injuries)          ||
    !isArrayEqual(plan.profileSnapshot?.medicalConditions, user.medicalConditions);

  if (shouldRegenerate) {
    console.log('♻️ Caching mismatch detected. Regenerating fresh workout plan...');
    plan = await generateAndSaveWorkoutPlan(user);
  } else {
    console.log('✅ Existing workout plan reused');
  }
  return plan;
};

// ─── GENERATE & SAVE DIET ────────────────────────────────────────────────────

const generateAndSaveDietPlan = async (user) => {
  let recommendationId = null;
  let weeklyPlan       = [];

  const activityLevel      = normalizeActivityLevel(user.activityLevel);
  const dietTypeNormalized = normalizeDietType(user.dietType);

  const bmr = dietCalculator.calculateBMR({
    gender: user.gender,
    weight: Number(user.weight) || 70,
    height: Number(user.height) || 170,
    age:    Number(user.age)    || 30
  });

  const tdee = dietCalculator.calculateTDEE(
    bmr,
    activityLevel,
    (user.medicalConditions && user.medicalConditions.length > 0) ? user.medicalConditions.join(' ') : 'Regular'
  );

  const dailyNutrition = generateDietPlan({
    tdee,
    weight: Number(user.weight) || 70,
    goal:   normalizeGoal(user.goal)
  });

  try {
    const response = await axios.post(`${ML_API_URL}/diet-recommendation`, {
      dietType:     dietTypeNormalized,
      noOnion:      !!user.noOnion,
      noGarlic:     !!user.noGarlic,
      glutenFree:   !!user.glutenFree,
      lactoseFree:  !!user.lactoseFree,
      nutAllergy:   !!user.nutAllergy,
      sugarFree:    !!user.sugarFree,
      calories:     dailyNutrition.calories,
      activityLevel,
      goal:         user.goal,
      disease: (user.medicalConditions && user.medicalConditions.length > 0) ? user.medicalConditions.join(' ') : 'none',
      injury:  (user.injuries          && user.injuries.length          > 0) ? user.injuries.join(' ')          : 'none'
    }, { timeout: 6000 });

    weeklyPlan       = response.data.weekly_plan       || [];
    recommendationId = response.data.recommendation_id || null;

    weeklyPlan = sanitizeDietPlanForPreferences(
      weeklyPlan,
      dietTypeNormalized,
      {
        noOnion:     !!user.noOnion,
        noGarlic:    !!user.noGarlic,
        glutenFree:  !!user.glutenFree,
        lactoseFree: !!user.lactoseFree,
        nutAllergy:  !!user.nutAllergy,
        sugarFree:   !!user.sugarFree
      }
    );

    console.log('✅ ML DIET PLAN GENERATED');
  } catch (error) {
    console.warn('Diet recommendation service unavailable:', error.message || error);
  }

  if (!Array.isArray(weeklyPlan) || weeklyPlan.length !== 7 || isFlatWeeklyPlan(weeklyPlan)) {
    console.log('⚠️ Using fallback diet generator');
    weeklyPlan = Array.from({ length: 7 }).map((_, index) =>
      createDailyDietDay(index, dailyNutrition.calories, dietTypeNormalized, {
        noOnion:     !!user.noOnion,
        noGarlic:    !!user.noGarlic,
        glutenFree:  !!user.glutenFree,
        lactoseFree: !!user.lactoseFree,
        nutAllergy:  !!user.nutAllergy,
        sugarFree:   !!user.sugarFree
      }, dailyNutrition)
    );
  }

  // Add a persistent date to each day of the plan to allow for correct frontend rotation.
  // This ensures the alignment logic on the client-side has a stable anchor date.
  const weekStart = getMondayStart();
  const datedWeeklyPlan = weeklyPlan.map((day, index) => {
    const currentDate = new Date(weekStart);
    currentDate.setDate(currentDate.getDate() + index);
    const isoDate = `${currentDate.getFullYear()}-${String(currentDate.getMonth() + 1).padStart(2, '0')}-${String(currentDate.getDate()).padStart(2, '0')}`;
    return {
      ...toPlainObject(day),
      date: isoDate,
    };
  });

  const filter  = { userId: user._id };

  const payload = {
    userId:       user._id,
    goal:         normalizeGoal(user.goal),
    dietType:     dietTypeNormalized,
    activityLevel,
    preferences:  {
      noOnion:     !!user.noOnion,
      noGarlic:    !!user.noGarlic,
      glutenFree:  !!user.glutenFree,
      lactoseFree: !!user.lactoseFree,
      nutAllergy:  !!user.nutAllergy,
      sugarFree:   !!user.sugarFree
    },
    weeklyPlan: datedWeeklyPlan,
    generatedAt:      new Date(),
    planSource:       'ml',
    recommendationId: recommendationId ? String(recommendationId) : null,
    profileSnapshot:  {
      goal:              normalizeGoal(user.goal),
      dietType:          dietTypeNormalized,
      noOnion:           !!user.noOnion,
      noGarlic:          !!user.noGarlic,
      glutenFree:        !!user.glutenFree,
      lactoseFree:       !!user.lactoseFree,
      nutAllergy:        !!user.nutAllergy,
      sugarFree:         !!user.sugarFree,
      medicalConditions: user.medicalConditions || ['Regular'],
      injuries:          user.injuries          || ['Regular']
    }
  };

  await UserDietPlan.replaceOne(filter, payload, { upsert: true });
  const updatedPlan = await UserDietPlan.findOne(filter);

  console.log('✅ DIET PLAN SAVED');
  return updatedPlan;
};

// ─── GET OR CREATE DIET ──────────────────────────────────────────────────────

const getOrCreateDietPlan = async (user) => {
  let dietPlan = await UserDietPlan.findOne({ userId: user._id }).lean();

  const shouldRegenerateDiet =
    !dietPlan ||
    !Array.isArray(dietPlan.weeklyPlan) ||
    dietPlan.weeklyPlan.length !== 7 ||
    !dietPlan.profileSnapshot ||
    dietPlan.profileSnapshot.goal         !== normalizeGoal(user.goal)         ||
    dietPlan.profileSnapshot.dietType     !== normalizeDietType(user.dietType) ||
    dietPlan.profileSnapshot.noOnion      !== !!user.noOnion                   ||
    dietPlan.profileSnapshot.noGarlic     !== !!user.noGarlic                  ||
    dietPlan.profileSnapshot.glutenFree   !== !!user.glutenFree                ||
    dietPlan.profileSnapshot.lactoseFree  !== !!user.lactoseFree               ||
    dietPlan.profileSnapshot.nutAllergy   !== !!user.nutAllergy                ||
    dietPlan.profileSnapshot.sugarFree    !== !!user.sugarFree                 ||
    !isArrayEqual(dietPlan.profileSnapshot?.medicalConditions, user.medicalConditions) ||
    !isArrayEqual(dietPlan.profileSnapshot?.injuries,          user.injuries);

  if (shouldRegenerateDiet) {
    console.log('♻️ Regenerating diet plan...');
    dietPlan = await generateAndSaveDietPlan(user);
  } else {
    console.log('✅ Existing diet plan reused');
  }

  return dietPlan;
};

// ─── FULL REGENERATION ───────────────────────────────────────────────────────

const regenerateUserPlans = async (user) => {
  console.log('♻️ Regenerating ALL plans...');
  const workoutPlan = await generateAndSaveWorkoutPlan(user);
  const dietPlan    = await generateAndSaveDietPlan(user);
  return { workoutPlan, dietPlan };
};

// ─── EXPORTS ─────────────────────────────────────────────────────────────────

module.exports = {
  getOrCreateWorkoutPlan,
  getOrCreateDietPlan,
  regenerateUserPlans,
  applyDifficultyScalingToPlan,
  createDailyDietDay,
  normalizeDietType
};