const mongoose = require("mongoose");

const workoutPlanSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true
  },

  title: {
    type: String,
    required: true,
    trim: true
  },

  goal: {
    type: String,
    enum: ["Weight Loss", "Muscle Gain", "Maintenance"],
    required: true
  },

  experienceLevel: {
    type: String,
    enum: ["Beginner", "Intermediate", "Advanced"],
    required: true
  },

  durationWeeks: {
    type: Number,
    default: 4
  },

  daysPerWeek: {
    type: Number,
    min: 1,
    max: 7,
    default: 5
  },

  exercises: [
    {
      name: {
        type: String,
        required: true
      },
      muscleGroup: {
        type: String,
        enum: [
          "chest",
          "back",
          "shoulders",
          "biceps",
          "triceps",
          "quads",
          "hamstrings",
          "glutes",
          "calves",
          "core",
          "full body"
        ],
        required: true
      },
      sets: {
        type: Number,
        required: true
      },
      reps: {
        type: Number,
        required: true
      },
      restSeconds: {
        type: Number,
        default: 60
      }
    }
  ],

  notes: {
    type: String,
    default: ""
  },

  // ✅ NEW: Persists the adaptive difficulty coefficient between sessions.
  // 1.0 = baseline. >1.0 = plan was too easy (volume increased). <1.0 = deload active.
  difficultyCoefficient: {
    type: Number,
    default: 1.0,
    min: 0.5,
    max: 2.0
  },

  weeklyPlan: {
    type: Array,
    default: []
  },

  isAutoGenerated: {
    type: Boolean,
    default: false
  },

  generatedAt: {
    type: Date,
    default: Date.now
  },

  planSource: {
    type: String,
    default: 'manual'
  },

  recommendationId: {
    type: String,
    default: null
  },

  profileSnapshot: {
    goal: {
      type: String,
      trim: true
    },
    experience: {
      type: String,
      trim: true
    },
    injuries: {
      type: Array,
      default: []
    },
    medicalConditions: {
      type: Array,
      default: []
    }
  },

  status: {
    type: String,
    enum: ["active", "archived"],
    default: "active"
  }
}, 
{ timestamps: true });

module.exports = mongoose.model("WorkoutPlan", workoutPlanSchema);